// ── Contracts Mock Data ──────────────────────────────────────────────────────

export type ContractType = 'MSA' | 'SLA' | 'PSA' | 'Addendum' | 'NDA';
export type ContractStatus = 'Active' | 'Expiring Soon' | 'Under Review' | 'Pending Renewal' | 'Expired';
export type AlertChannel = 'Email' | 'Teams' | 'SMS';
export type AlertDelivery = 'Delivered' | 'Failed' | 'Pending';

export interface Contract {
  id: string;
  client: string;
  type: ContractType;
  valueMonthly: number;
  valueAnnual: number;
  startDate: string;
  endDate: string;
  autoRenew: boolean;
  status: ContractStatus;
  healthScore: number;
  contactName: string;
  contactEmail: string;
  daysUntilRenewal: number;
  industry: string;
}

export interface AlertActivity {
  id: string;
  contractId: string;
  client: string;
  channel: AlertChannel;
  message: string;
  sentAt: string;
  delivery: AlertDelivery;
  recipient: string;
}

export const CONTRACTS: Contract[] = [
  {
    id: 'c001',
    client: 'Apex Dynamics',
    type: 'MSA',
    valueMonthly: 18500,
    valueAnnual: 222000,
    startDate: '2024-04-01',
    endDate: '2026-03-31',
    autoRenew: true,
    status: 'Expiring Soon',
    healthScore: 88,
    contactName: 'Rachel Kim',
    contactEmail: 'rkim@apexdynamics.io',
    daysUntilRenewal: 14,
    industry: 'SaaS',
  },
  {
    id: 'c002',
    client: 'CloudVault Systems',
    type: 'SLA',
    valueMonthly: 12200,
    valueAnnual: 146400,
    startDate: '2024-07-15',
    endDate: '2026-04-15',
    autoRenew: false,
    status: 'Pending Renewal',
    healthScore: 72,
    contactName: 'Jason Park',
    contactEmail: 'jpark@cloudvault.com',
    daysUntilRenewal: 29,
    industry: 'Cloud Infrastructure',
  },
  {
    id: 'c003',
    client: 'NovaTech Partners',
    type: 'PSA',
    valueMonthly: 9800,
    valueAnnual: 117600,
    startDate: '2023-06-01',
    endDate: '2026-05-01',
    autoRenew: true,
    status: 'Active',
    healthScore: 94,
    contactName: 'Priya Sharma',
    contactEmail: 'priya@novatech.ai',
    daysUntilRenewal: 45,
    industry: 'AI / ML',
  },
  {
    id: 'c004',
    client: 'MedCore Health',
    type: 'MSA',
    valueMonthly: 22400,
    valueAnnual: 268800,
    startDate: '2024-01-01',
    endDate: '2026-04-30',
    autoRenew: true,
    status: 'Expiring Soon',
    healthScore: 91,
    contactName: 'Dr. Alan Foster',
    contactEmail: 'afoster@medcore.health',
    daysUntilRenewal: 44,
    industry: 'Healthcare',
  },
  {
    id: 'c005',
    client: 'Meridian Logistics',
    type: 'SLA',
    valueMonthly: 7600,
    valueAnnual: 91200,
    startDate: '2025-03-01',
    endDate: '2026-06-01',
    autoRenew: false,
    status: 'Active',
    healthScore: 85,
    contactName: 'Tony Vargas',
    contactEmail: 'tvargas@meridianlog.com',
    daysUntilRenewal: 76,
    industry: 'Logistics',
  },
  {
    id: 'c006',
    client: 'SkyBridge Capital',
    type: 'MSA',
    valueMonthly: 31000,
    valueAnnual: 372000,
    startDate: '2023-10-01',
    endDate: '2026-06-30',
    autoRenew: true,
    status: 'Active',
    healthScore: 97,
    contactName: 'Evelyn Cho',
    contactEmail: 'echo@skybridgecap.com',
    daysUntilRenewal: 105,
    industry: 'Fintech',
  },
  {
    id: 'c007',
    client: 'Pinnacle DevOps',
    type: 'PSA',
    valueMonthly: 8900,
    valueAnnual: 106800,
    startDate: '2024-09-01',
    endDate: '2026-03-24',
    autoRenew: false,
    status: 'Expiring Soon',
    healthScore: 61,
    contactName: 'Marcus Webb',
    contactEmail: 'mwebb@pinnacledevops.co',
    daysUntilRenewal: 7,
    industry: 'DevOps / Platform',
  },
  {
    id: 'c008',
    client: 'OrbitX Technologies',
    type: 'SLA',
    valueMonthly: 15300,
    valueAnnual: 183600,
    startDate: '2024-12-01',
    endDate: '2026-07-01',
    autoRenew: true,
    status: 'Active',
    healthScore: 89,
    contactName: 'Nadia Laurent',
    contactEmail: 'nlaurent@orbitx.tech',
    daysUntilRenewal: 106,
    industry: 'Aerospace Tech',
  },
  {
    id: 'c009',
    client: 'Vector9 Analytics',
    type: 'Addendum',
    valueMonthly: 4200,
    valueAnnual: 50400,
    startDate: '2025-01-15',
    endDate: '2026-04-15',
    autoRenew: true,
    status: 'Pending Renewal',
    healthScore: 78,
    contactName: 'Sam Okafor',
    contactEmail: 'sokafor@vector9.io',
    daysUntilRenewal: 29,
    industry: 'Data Analytics',
  },
  {
    id: 'c010',
    client: 'Stratos Security',
    type: 'MSA',
    valueMonthly: 19700,
    valueAnnual: 236400,
    startDate: '2023-08-01',
    endDate: '2026-07-31',
    autoRenew: true,
    status: 'Active',
    healthScore: 96,
    contactName: 'Ingrid Holt',
    contactEmail: 'iholt@stratossec.com',
    daysUntilRenewal: 136,
    industry: 'Cybersecurity',
  },
  {
    id: 'c011',
    client: 'Nexus Biotech',
    type: 'SLA',
    valueMonthly: 11100,
    valueAnnual: 133200,
    startDate: '2024-05-01',
    endDate: '2026-04-01',
    autoRenew: false,
    status: 'Under Review',
    healthScore: 74,
    contactName: 'Dr. Kenji Mori',
    contactEmail: 'kmori@nexusbiotech.com',
    daysUntilRenewal: 15,
    industry: 'Biotech',
  },
  {
    id: 'c012',
    client: 'Quantum Shift Labs',
    type: 'PSA',
    valueMonthly: 6600,
    valueAnnual: 79200,
    startDate: '2025-02-01',
    endDate: '2026-08-01',
    autoRenew: true,
    status: 'Active',
    healthScore: 83,
    contactName: 'Zoe Callahan',
    contactEmail: 'zcallahan@qslabs.dev',
    daysUntilRenewal: 137,
    industry: 'Deep Tech',
  },
  {
    id: 'c013',
    client: 'Harbor Point Finance',
    type: 'MSA',
    valueMonthly: 27500,
    valueAnnual: 330000,
    startDate: '2023-11-01',
    endDate: '2026-05-15',
    autoRenew: true,
    status: 'Active',
    healthScore: 92,
    contactName: 'Claire Ashford',
    contactEmail: 'cashford@harborpoint.com',
    daysUntilRenewal: 59,
    industry: 'Finance',
  },
  {
    id: 'c014',
    client: 'TerraGrid Energy',
    type: 'NDA',
    valueMonthly: 3400,
    valueAnnual: 40800,
    startDate: '2025-01-01',
    endDate: '2026-04-20',
    autoRenew: false,
    status: 'Pending Renewal',
    healthScore: 67,
    contactName: 'Brett Olsen',
    contactEmail: 'bolsen@terragrid.energy',
    daysUntilRenewal: 34,
    industry: 'Energy',
  },
  {
    id: 'c015',
    client: 'Luminary Studios',
    type: 'SLA',
    valueMonthly: 5500,
    valueAnnual: 66000,
    startDate: '2024-11-01',
    endDate: '2026-09-01',
    autoRenew: true,
    status: 'Active',
    healthScore: 88,
    contactName: 'Aiko Tanaka',
    contactEmail: 'atanaka@luminarystudios.com',
    daysUntilRenewal: 168,
    industry: 'Media & Creative',
  },
];

export const ALERT_ACTIVITY: AlertActivity[] = [
  {
    id: 'a001',
    contractId: 'c007',
    client: 'Pinnacle DevOps',
    channel: 'Email',
    message: '7-day renewal alert — contract expires 2026-03-24. Immediate action required.',
    sentAt: '2026-03-17 09:00:02',
    delivery: 'Delivered',
    recipient: 'mwebb@pinnacledevops.co',
  },
  {
    id: 'a002',
    contractId: 'c007',
    client: 'Pinnacle DevOps',
    channel: 'SMS',
    message: 'URGENT: Your MSP contract expires in 7 days. Contact your account manager.',
    sentAt: '2026-03-17 09:00:05',
    delivery: 'Delivered',
    recipient: '+1 415-555-0192',
  },
  {
    id: 'a003',
    contractId: 'c001',
    client: 'Apex Dynamics',
    channel: 'Teams',
    message: '14-day renewal alert — MSA contract expiring 2026-03-31.',
    sentAt: '2026-03-17 08:45:11',
    delivery: 'Delivered',
    recipient: '#contracts-alerts',
  },
  {
    id: 'a004',
    contractId: 'c011',
    client: 'Nexus Biotech',
    channel: 'Email',
    message: '15-day renewal alert — SLA under review, renewal negotiation required.',
    sentAt: '2026-03-17 08:30:44',
    delivery: 'Delivered',
    recipient: 'kmori@nexusbiotech.com',
  },
  {
    id: 'a005',
    contractId: 'c002',
    client: 'CloudVault Systems',
    channel: 'Email',
    message: '30-day renewal alert — SLA contract expiring 2026-04-15. No auto-renew set.',
    sentAt: '2026-03-16 09:00:03',
    delivery: 'Delivered',
    recipient: 'jpark@cloudvault.com',
  },
  {
    id: 'a006',
    contractId: 'c009',
    client: 'Vector9 Analytics',
    channel: 'Email',
    message: '30-day renewal alert — Addendum expiring 2026-04-15.',
    sentAt: '2026-03-16 09:00:07',
    delivery: 'Delivered',
    recipient: 'sokafor@vector9.io',
  },
  {
    id: 'a007',
    contractId: 'c004',
    client: 'MedCore Health',
    channel: 'Teams',
    message: '45-day renewal notice — MSA auto-renew enabled, verify terms before renewal.',
    sentAt: '2026-03-14 09:00:01',
    delivery: 'Delivered',
    recipient: '#medcore-account',
  },
  {
    id: 'a008',
    contractId: 'c014',
    client: 'TerraGrid Energy',
    channel: 'SMS',
    message: '30-day alert: NDA expiring 2026-04-20. No auto-renew. Contact required.',
    sentAt: '2026-03-16 09:01:02',
    delivery: 'Failed',
    recipient: '+1 408-555-0177',
  },
];

export const REVENUE_AT_RISK = {
  total: 247800,
  contractsCount: 3,
  breakdown: [
    { window: '< 30 days', amount: 102300, contracts: 2 },
    { window: '30–60 days', amount: 82600, contracts: 3 },
    { window: '60–90 days', amount: 62900, contracts: 2 },
  ],
};
